apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: test
spec:
   containers:
      - name: my-con
        image: nginx
        ports:
           - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
      app: test
  type: NodePort   
  #type: LoadBalancer  
  ports:
     - port: 80
       targetPort: 80    
