apiVersion: apps/v1
kind: Deployment
metadata:
   name: my-deploy
   labels:
      app: dev
spec:
   replicas: 3
   selector:  
      matchLabels:
         app: dev
   template:
      metadata:
         labels:
            app: dev
      spec:
         containers:
           - name: mycon
             image: nginx
             ports:
                - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-deploy
spec:
   selector:
      app: dev
   type: NodePort
   #type: LoadBalancer  
   ports:
     - port: 80
       targetPort: 80     
