apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
spec:
  replicas: 3
  selector:
    color: blue
  template:
    metadata:
      name: nginx
      labels:
        color: blue
    spec:
      containers:
      - name: mycon
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: rc-service
spec:
   type: NodePort
   selector:
     color: blue
   ports:
     - port: 80
       targetPort: 80     
