apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
  labels:
    color: red
spec:
  replicas: 3
  selector:
    matchLabels:
      color: red
  template:
    metadata:
      labels:
        color: red
    spec:
      containers:
        - name: mycon
          image: nginx
          ports:
           - containerPort: 80  
---
apiVersion: v1
kind: Service
metadata:
  name: rs-service
spec:
   selector:
       color: red
   type: NodePort
   #type: LoadBalancer
   ports:
     - port: 80
       targetPort: 80     
